name: node-ci

on: [push]

jobs:
  lint:
    # Checkout, install dependencies, typecheck, and lint
    name: Typecheck and lint

    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install dependencies
        run: npm install

      - name: Typecheck
        run: tsc --noEmit

      - name: Lint
        run: npm run lint
